apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-postgres
spec:
  schedule: "*/30 * * * *"  # Cada 30 minutos
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup
              image: postgres:16
              command: ["/bin/sh", "-c"]
              args:
                - PGPASSWORD=admin pg_dump -h postgres -U postgres -d postgresdb > /backup/backup-$(date +\%Y-\%m-\%d_\%H-\%M-\%S).sql
              volumeMounts:
                - name: backup-volume
                  mountPath: /backup
          restartPolicy: OnFailure
          volumes:
            - name: backup-volume
              hostPath:
                path: /mnt/data/backups
                type: DirectoryOrCreate
