version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: postgresdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  create-ms:
    build: ./create
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  read-ms:
    build: ./list
    ports:
      - "8081:8080"
    depends_on:
      - postgres

  update-ms:
    build: ./update
    ports:
      - "8082:8080"
    depends_on:
      - postgres

  delete-ms:
    build: ./delete
    ports:
      - "8083:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
